### ISSUE TITLE
Enhance the code of Linked-List/SegregateEvenOdd

### ISSUE THREAD

**Issue by codea-holic** [codea-holic/Advance-data-structure-java#4]
**Modify code of SegregateEvenOdd.java** 

This code successfully runs but the need is that the order of number should not be changed.

Input:-
```
5
3 9 7 8 4
```

Required Output:-
```
8 4 3 9 7
```

My Output:-
```
8 4 7 3 9 
```

This file is uploaded with commit 07da906721cbb3c6224d92b2ef6b87fd3f85d001

**Comment by codea-holic** [comment]
This file is uploaded with commit 07da906721cbb3c6224d92b2ef6b87fd3f85d001.

**Comment by shreegilliorkar** [comment]
Hey @codea-holic,  i would like to contribute to this project. Can you please give me details about this issue also about why you want the list output in this order only.

**Comment by codea-holic** [comment]
Yeah Sure, It's simply a question related to Linked List. This code is not linked with any of the files. It's a challenge only.
The question is explained in my above comment.
 _If you think information is not sufficient then message._

**Comment by shreegilliorkar** [comment]
okay @codea-holic , I will try to look into this issue and try to solve it. If any doubt came, I will contact you.

**Comment by shreegilliorkar** [comment]
@codea-holic, The result which you were getting was because you were swapping the positions of even and odd. If we do it in that way you will not get that sequence. The reason is after swapping the list is not in the correct order as the user entered it. I updated the code according to the required output. You can have a look and let me know if any changes are required.
